### ISSUE TITLE
unable to grab key on email

### ISSUE THREAD

**Issue by peterpt** [skiddie/metasploit-pro-trial-grabber#10]
Hi , nice script however there is an issue with it .

the message is simple :
"reaching the maximum retry count exiting"
 or the email did not arrived or there is some issue with the script that is unable to get the key .
during the process everything is completely correctly by the script , it only have issues getting the key .

note : i tried several times with the same result .

**Comment by skiddie** [comment]
Hi @peterpt,

after a little survey, so sorry to let you know that **this script wont work** in the future any more.
cause trial page is using [Google reCAPTCHA](https://www.google.com/recaptcha/intro/index.html) to avoid the auto-scripts now.
anyway, thanks for your feedback :beers:

Chris

**Comment by peterpt** [comment]
Is it possible for you in the script reedirect to web browser for user interaction (to pass the captcha) , and then capture the cookie and complete the procedure normally ?
If not then reedirect to webbrowser and user will do the rest .

**Comment by skiddie** [comment]
Hi again,

first, thanks for your feedback.
it's not really easy to implement your idea in script.

if the trial page is using old captcha verification ..
it's possible to use **OCR** or **[online recognition service](http://antigate.com/)** to bypass it.

but Rapid7 is using new reCAPTCHA now, i dont think it can be bypassed easily.
about redirection, you can try to browse [here](http://goo.gl/7aapY2) and this link will fill some fileds automatically.
maybe all you wants is a browser's plugin to auto-fill the fields, and you manual click captcha.

Chris

**Comment by laapsaap** [comment]
This was really favorite script ever. Really badass, too bad about the new captcha
