### ISSUE TITLE
cURL error in the end 

### ISSUE THREAD

**Issue by BpArCuCTeMbI** [skiddie/metasploit-pro-trial-grabber#9]
php execute.php
[+] defining the pre-required constants .. DONE !
[+] loading the 3rd-party libraries .. DONE !
[+] creating all classes' instance .. DONE !
[+] checking all mail domains from provider: Yopmail are valid or not ..
  [-] parsing all the available domains from response .. DONE !
    [*] parsing the profile fields from response .. DONE !
    [*] parsing the additional info from response .. DONE !
      [-] extracting from all the available domains ..
        [*] checking the mail address: bentoges95@yopmail.fr is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@yopmail.net is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@cool.fr.nf is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@jetable.fr.nf is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@nospam.ze.tc is valid or not .. VALID !
        [*] checking the mail address: bentoges95@nomail.xl.cx is valid or not .. VALID !
        [*] checking the mail address: bentoges95@mega.zik.dj is valid or not .. VALID !
        [*] checking the mail address: bentoges95@speed.1s.fr is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@courriel.fr.nf is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@moncourrier.fr.nf is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@monemail.fr.nf is valid or not .. ILLEGAL
        [*] checking the mail address: bentoges95@monmail.fr.nf is valid or not .. ILLEGAL
      [-] ALL DONE !
[+] ALL DONE !
[+] choosing a valid domain and generating an email address .. DONE !

[+] READY TO FIRE !

[+] submitting the trial request to metasploit ..
  [-] parsing the hidden filds' value from response ..
      [*] field: custparamleadsource has value: 3150667
      [*] field: submitted has value:
      [*] field: custparamproductaxscode has value: W8PL6ZgWHf
      [*] field: custparamthisIP has value: 10.250.0.110
      [*] field: custparamredirectcode has value: FL55F
      [*] field: custparam_lrpsid has value: 1771314789132350
  [-] ALL DONE !
  [-] preparing the registration payload .. DONE !
  [-] sending the registration data to online form .. DONE !
[+] ALL DONE !
[+] looping to retrieve the trial mail content ..
  [-] checking the trial confirmation mail has delivered to inbox or not ..
      [*] BINGO ! the mail just delivered, parsing it .. PHP Notice:  Undefined offset: 0 in /home/metasploit-pro-trial-grabber/execute.php on line 525

[?] cURL error occurred ..
[?] error code: 410
[?] error message: HTTP/1.0 410 Gone

So, this is it.On windows and on linux it's all the same error.

**Comment by skiddie** [comment]
Hi @BpArCuCTeMbI,

thanks for your feedback.
i found that yopmail's [rss feed](http://www.yopmail.com/en/rss.php?login=outramer) is using [Google reCAPTCHA](https://www.google.com/recaptcha/intro/index.html) now.

please consider to use Spambog to fetch license, thank you :smiley:
